### ISSUE TITLE
support OpenAPI "deprecated" property

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-core#10]
### properties

**in:**

```
  schemas:
    Foo:
      type: object
      properties:
        bar:
          type: string
          deprecated: true  
```

**out:**

```
class Foo {

    @Deprecated
    @JsonProperty("bar")
    private String bar;

     //.....
}
```

### endpoints

**in:**

```
paths:
  /foo:
    get:
      # ....
      deprecated: true
```

**out:**
```
interface Foo {

    @Deprecated
    @GetMapping(path = "/foo")
    void getFoo();
    // ....
}
