### ISSUE TITLE
Mapping to Generated Types with shortcut

### ISSUE THREAD

**Issue by schlagi123** [openapi-processor/openapi-processor-core#20]
Currently I reference in a Mapping a self generated resource:

```
openapi-processor-mapping: v2
options:
  package-name: de.test.generated
map:
  types:
    - type: UserPageResource => org.springframework.data.domain.Page<de.test.generated.UserResource>
```

I think it would a nice idea to reference a generated typ directly and not other the java type. e. g:
```
    - type: UserPageResource => org.springframework.data.domain.Page<UserResource>
``` 
or
```
    - type: UserPageResource => org.springframework.data.domain.Page<*UserResource>
``` 
or somthing like that.
