### ISSUE TITLE
parse "?" generic parameter to an explicit object instead of an empty list

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-core#30]
passing a `HttpRequest` to a (Micronaut) controller without providing a body type uses a parameter like this (in kotlin):

```kotlin
request: HttpRequest<*>
```

the mapping to add the parameter is:

```yaml
map:
  paths:
    /foo:
      parameters:
        - add: request => io.micronaut.http.HttpRequest<?>
```

Currently this translates to an empty generic parameter list, i.e. the generated java parameter is just

```java
void foo(HttpRequest request);
```

this shows a warning in IDEA:  *Raw use of parameterized class 'HttpRequest'*

The kotlin implementation can implement it as

```kotlin
override fun foo(request: HttpRequest<*>)
```

but it would be nice to generate the java endpoint with generic parameter to remove the warning

```java
void foo(HttpRequest<?> request);
```
