### ISSUE TITLE
endpoint mapping by http method

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-core#54]
currently the endpoint mappings are applied to all http methods of a single endpoint:

```
openapi-processor-mapping: v2.0
    
map:
  paths:
    /foo:
      parameters:
        - add: request => javax.servlet.http.HttpServletRequest
```

It should be possible to configure an endpoint mapping only for a specific http method:
 
```
openapi-processor-mapping: v2.0
    
map:
  paths:
    /foo:
      get:
        parameters:
          - add: request => javax.servlet.http.HttpServletRequest
```
