### ISSUE TITLE
allow endpoint mapping by http method

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-core#55]
currently an endpoint specific mapping applies to all http methods. This limits the usefulness of the endpoint mapping because you don't always need/want the mapping for all http methods. 

this applies the mappings to all methods (current behaviour):

```
openapi-processor-mapping: v2

map:
  paths:
    /foo:
      types:
        - type: from => to
```

this applies the mappings only to the given http method (new/additional behaviour):

```
openapi-processor-mapping: v2

map:
  paths:
    /foo:
      get:
        types:
          - type: A => B

      patch:
        types:
          - type: A => C
```
