### ISSUE TITLE
modelNameSuffix

### ISSUE THREAD

**Issue by aegliv** [openapi-processor/openapi-processor-core#65]
Hi,

awesome project, thanks for putting in the hours!

The `openapi-generator-maven-plugin` has a configuration property called `modelNameSuffix` which, as the name suggest, allows the user to append a suffix to the generated model classes.

Do you thing such a feature would be valuable in your project as well?

### Example
Swagger:
```yaml
components:
  schemas:
    FooObject:
      type: object
      properties:
        bar:
          type: boolean
```
Mapping:
```yaml
openapi-processor-mapping: v2

options:
   package-name: example.gen

   modelNameSuffix: Dto
```
Would result in the generation of `example.gen.model.FooObjectDto.java`

**Comment by hauner** [comment]
Funny, haven't thought of that.  :-)

Yes, I guess this would be useful. That way we can avoid the postfix "noise" in the openapi description, which is our current strategy at work.. ;-)

**Comment by hauner** [comment]
@aegliv I think it should work now. Tests pass but I haven't tried it on a real project yet.

You can try the latest openapi-processor-spring snapshot (2021.4-SNAPSHOT) (or openapi-processor-micronaut 2021.2-SNAPSHOT). Just update the version.

The mapping looks like this:

```yaml
openapi-processor-mapping: v2

options:
  package-name: generated
  model-name-suffix: Resource
```

It will ignore the suffix if the schema already ends with the suffix to ease migration.
