### ISSUE TITLE
allOf does not filter duplicate properties

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-core#85]
a schema with `allOf` and properties with the same name

```yaml
  schema:
    allOf:
      - type: object
        properties:
          foo:
            type: string
      - type: object
        properties:
          foo:
            type: string
```

will generate a class with two `foo` properties
