### ISSUE TITLE
schema with `allOf` and `properties` on the same level

### ISSUE THREAD

**Issue by hauner** [openapi-processor/openapi-processor-core#86]
the processor ignores the  `properties` of a schema that's using `allOf` on the same level:

```yaml
  schema:
    type: object
    allOf:
      - type: object
        properties:
          prop1:
            type: string
    properties:
      prop2:
        type: string
```

from: https://github.com/openapi-processor/openapi-processor-maven/issues/2
